// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEmpleo.Data;

#nullable disable

namespace PlataformaEmpleo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlataformaEmpleo.Models.CV", b =>
                {
                    b.Property<int>("IdCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCV"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<string>("ExperienciaLaboral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormacionAcademica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idiomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCV");

                    b.HasIndex("CandidatoId")
                        .IsUnique();

                    b.ToTable("CV");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Candidato", b =>
                {
                    b.Property<int>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidato"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdCandidato");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.OfertaEmpleo", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReclutadorId")
                        .HasColumnType("int");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOferta");

                    b.HasIndex("ReclutadorId");

                    b.ToTable("OfertaEmpleo");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.OfertaPostulacion", b =>
                {
                    b.Property<int>("OfertasPostulacionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfertasPostulacionesId"));

                    b.Property<int>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("IdPostulacion")
                        .HasColumnType("int");

                    b.HasKey("OfertasPostulacionesId");

                    b.HasIndex("IdOferta");

                    b.HasIndex("IdPostulacion");

                    b.ToTable("OfertaPostulacion");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Postulacion", b =>
                {
                    b.Property<int>("IdPostulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPostulacion"));

                    b.Property<int>("EstadoPostulacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCandidato")
                        .HasColumnType("int");

                    b.Property<int?>("OfertaEmpleoIdOferta")
                        .HasColumnType("int");

                    b.HasKey("IdPostulacion");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("OfertaEmpleoIdOferta");

                    b.ToTable("Postulacion");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Reclutador", b =>
                {
                    b.Property<int>("IdReclutador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReclutador"));

                    b.Property<string>("correoEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReclutador");

                    b.ToTable("Reclutador");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.CV", b =>
                {
                    b.HasOne("PlataformaEmpleo.Models.Candidato", "candidato")
                        .WithOne("cv")
                        .HasForeignKey("PlataformaEmpleo.Models.CV", "CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("candidato");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.OfertaEmpleo", b =>
                {
                    b.HasOne("PlataformaEmpleo.Models.Reclutador", "Reclutador")
                        .WithMany("OfertasDeTrabajo")
                        .HasForeignKey("ReclutadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reclutador");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.OfertaPostulacion", b =>
                {
                    b.HasOne("PlataformaEmpleo.Models.OfertaEmpleo", "ofertaEmpleo")
                        .WithMany()
                        .HasForeignKey("IdOferta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEmpleo.Models.Postulacion", "postulacion")
                        .WithMany("ofertasPostulaciones")
                        .HasForeignKey("IdPostulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ofertaEmpleo");

                    b.Navigation("postulacion");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Postulacion", b =>
                {
                    b.HasOne("PlataformaEmpleo.Models.Candidato", "candidato")
                        .WithMany("postulaciones")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEmpleo.Models.OfertaEmpleo", null)
                        .WithMany("postulacionesEmpleos")
                        .HasForeignKey("OfertaEmpleoIdOferta");

                    b.Navigation("candidato");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Candidato", b =>
                {
                    b.Navigation("cv")
                        .IsRequired();

                    b.Navigation("postulaciones");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.OfertaEmpleo", b =>
                {
                    b.Navigation("postulacionesEmpleos");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Postulacion", b =>
                {
                    b.Navigation("ofertasPostulaciones");
                });

            modelBuilder.Entity("PlataformaEmpleo.Models.Reclutador", b =>
                {
                    b.Navigation("OfertasDeTrabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
